USE WORLD;
DESCRIBE CITY;
SELECT COUNT(*)
FROM  CITY;


SELECT * FROM CITY;
SELECT * FROM COUNTRY;
SELECT * FROM  countryLanguage;



DROP DATABASE IF EXISTS GD;
CREATE DATABASE IF NOT EXISTS GD;
SHOW DATABASES;
USE GD;
SHOW TABLES;


-- One to One Relationship
DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT(
STUDENT_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
STUDENT_NAME VARCHAR(100)
);

CREATE TABLE ID_PROOF(
ADHARCARD VARCHAR(100),
STUDENT_ID INT UNSIGNED,
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);


INSERT INTO STUDENT(STUDENT_NAME) 
SELECT Full Name (In Revature Pro) 
FROM gd.ap_batch;


-- One to One Relationship
USE GD;
DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT(
STUDENT_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
STUDENT_NAME VARCHAR(100)
);

CREATE TABLE ADDRESS(
STUDENT_ID INT UNSIGNED ,
ADDRESS_LINE1 VARCHAR(100),
ADDRESS_LINE2 VARCHAR(100),
CITY VARCHAR(100),
ZIP VARCHAR(100),
STATE VARCHAR(100),
COUNTRY VARCHAR(100),
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT(
STUDENT_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
STUDENT_NAME VARCHAR(100)
);

CREATE TABLE CLASS(
CLASS_ID INT PRIMARY KEY,
COURSE_NAME VARCHAR(100)
);

CREATE TABLE BATCH(
STUDENT_ID INT UNSIGNED,
CLASS_ID INT,
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID)
);


SELECT * FROM gd.apbatch;
SELECT * FROM STUDENT;
USE GD;
INSERT INTO STUDENT(STUDENT_NAME)
SELECT FullName 
FROM gd.apbatch;

UPDATE STUDENT
SET STUDENT_NAME='G ---- D'
WHERE STUDENT_ID=1; 

DELETE FROM STUDENT
WHERE STUDENT_ID=2 OR STUDENT_ID=3; 


USE GD;
INSERT INTO student (student_name) 
(SELECT * FROM gd.list);